### ISSUE TITLE
Middle March Iteration Plan

### ISSUE THREAD

**Issue by alexrchies** [Stratio/egeo#114]
This plan captures the focus of our work during the first half of March iteration. It's a 2-week iteration. We will ship middle of March.

# Legend

We use the [MOSCOW notation](https://en.wikipedia.org/wiki/MoSCoW_method) to decide about the priority of tasks.

| Mark | Meaning |   
|---|---|
|  **[M]** | Must Have |
|  **[S]** | Should Have |
|  **[C]** | Could Have |
|  **[W]** | Won't Have |

# Iteration Goal

Launch the public version of the library.

# Tasks

- [x] **[M]** Did the Github repositories public @ppenalver 
- [x] **[M]** Create a user @stratio in npm @ppenalver 
- [ ] **[M]** Configure Jenkins to publish in npm on release @ppenalver 
- [x] **[S]** Write a good Readme.md - #102 @alexrchies
- [x] **[S]** Write tests to reach the 70% coverage in st-spinner - #70 @fjsc 
- [x] **[S]** Write tests to reach the 70% coverage in st-tooltip - #71 @EvaMGC 
- [x] **[S]** Library repo separated of web repo - #63 @ppenalver 
- [x] **[C]** Move the whole tasks in JIRA to Github @alexrchies
- [x] **[C]** Setup milestones, labels, etc in Github @alexrchies
- [x] **[C]** Create an issue template for Github - #101 @alexrchies

**Comment by ppenalver** [comment]
Jenkins task are pending to https://stratio.atlassian.net/browse/QA-350 and for this time we publish by manual way in npm.
