### ISSUE TITLE
End March Iteration Plan

### ISSUE THREAD

**Issue by alexrchies** [Stratio/egeo#132]
This plan captures the focus of our work during the first half of March iteration. It's a 2-week iteration. We will ship end of March.

# Legend

We use the [MOSCOW notation](https://en.wikipedia.org/wiki/MoSCoW_method) to decide about the priority of tasks.

| Mark | Meaning |   
|---|---|
|  **[M]** | Must Have |
|  **[S]** | Should Have |
|  **[C]** | Could Have |
|  **[W]** | Won't Have |

# Iteration Goal

Launch a complete and reviewed version of the documentation website

# Tasks

- [x] **[M]** Research about gh-pages @ppenalver #133 
- [x] **[M]** Research about waffle.io @ppenalver #134
- [x] **[M]** Get public URL for Egeo documentation #138  
- [x] **[M]** Review the whole documentation @abrahamnavas @alexrchies #136 
- [x] **[M]** Create project files (readme, license, contributing...) in egeo-web @alexrchies
- [x] **[M]** Create project files (readme, license, contributing...) in egeo-ui-base @alexrchies
- [x] **[M]** Create project files (readme, license, contributing...) in egeo-starter @alexrchies
- [x] **[M]** Create wiki in egeo-web @alexrchies
- [x] **[M]** Create wiki in egeo-ui-base @alexrchies
- [x] **[M]** Create wiki in egeo-starter @alexrchies
- [x] **[M]** Create issue and pr template in egeo-web @alexrchies
- [x] **[M]** Create issue and pr template in egeo-ui-base @alexrchies
- [x] **[M]** Create issue and pr template in egeo-starter @alexrchies
- [ ] **[M]** Refactor the whole components to thematize them and remove egeo-ui-base dependency 
- [x] **[S]** Publish space-around-components proposals
- [ ] **[S]** Put an avatar to our npm user @ppenalver 
- [x] **[S]** Research about RollUp @ppenalver 
- [x] **[S]** Remove st-table #128 
- [x] **[S]** Refactor st-modal @ppenalver 
- [x] **[S]** Design st-two-list @abrahamnavas 
- [x] **[S]** Finish st-modal @ppenalver 
- [x] **[C]** Re-birth the Egeo's G+ community @alexrchies 
- [x] **[C]** Automatize via npm scripts the commit, pre-commit, deploy, gh-pages... @ppenalver
- [x] **[C]** CI with Travis @ppenalver 
- [x] **[C]** Deploy egeo-web with Travis on gh-pages @ppenalver
- [ ] **[C]** Design login @mariasantanastratio
