### ISSUE TITLE
Middle April Iteration Plan

### ISSUE THREAD

**Issue by alexrchies** [Stratio/egeo#161]
This plan captures the focus of our work during the first half of April iteration. It's a 2-week iteration. We will ship middle of April.

# Legend

We use the [MOSCOW notation](https://en.wikipedia.org/wiki/MoSCoW_method) to decide about the priority of tasks.

| Mark | Meaning |   
|---|---|
|  **[M]** | Must Have |
|  **[S]** | Should Have |
|  **[C]** | Could Have |
|  **[W]** | Won't Have |

# Iteration Goal

Improve the quality and documentation of the platform, working on testing, documentation, and refinement of our methodology.

# Tasks

- [x] **[M]** Update documentation website with 1.3.0 components changes
- [ ] **[M]** Refactor components to move themifiable styles to egeo-theme #162
- [x] **[M]** Reach 70% coverage on branches #163
- [ ] **[M]** Integrate coveralls and force 70% coverage to let PR approve @ppenalver #164
- [x] **[M]** End login design @mariasantanastratio #106 
- [x] **[M]** st-radio component @pjpenast #83 
- [ ] **[M]** st-checkbox component @pjpenast #165
- [x] **[M]** Create a deprecated decorator #168
- [x] **[M]** Finish egeo-resolve @ppenalver #144 #77 #169
- [x] **[M]** Add commitizen to the whole projects @ppenalver 
- [ ] **[M]** Finish general styles in egeo-web @alexrchies @abrahamnavas 
- [ ] **[S]** st-switch component #166
- [ ] **[S]** Meeting about when document and deploy documentation on egeo-web
- [x] **[S]** Refactor physical board
- [x] **[S]** Upgrade to Angular 2.4.10 #170
- [x] **[S]** Design breadcrumb @mariasantanastratio @abrahamnavas #167 
- [ ] **[S]** Change issue and PR templates to work with commitizen @alexrchies
- [ ] **[C]** Open issue to set an avatar on @stratio user on npm @ppenalver 
- [ ] **[C]** Document egeo-cli @alexrchies @ppenalver 
- [x] **[C]** Research about code/sample plugin on egeo-website
- [ ] **[C]** Advances about stars in repos
- [x] **[C]** use angular-cli/webpack plugin on egeo-starter

**Comment by ppenalver** [comment]
Close this iteration, start next
