### ISSUE TITLE
End April iteration plan

### ISSUE THREAD

**Issue by ppenalver** [Stratio/egeo#194]
This plan captures the focus of our work during the first half of April iteration. It's a 2-week iteration. We will ship at end of April.

# Legend

We use the [MOSCOW notation](https://en.wikipedia.org/wiki/MoSCoW_method) to decide about the priority of tasks.

| Mark | Meaning |   
|---|---|
|  **[M]** | Must Have |
|  **[S]** | Should Have |
|  **[C]** | Could Have |
|  **[W]** | Won't Have |

# Iteration Goal

Improve the quality and documentation of the platform, working on testing, documentation, and refinement of our methodology.

# Tasks

- [x] **[M]** Rewrite bundle generation #211 
- [x] **[M]** Refactor components to move themifiable styles to egeo-theme #162
- [ ] **[M]** st-checkbox component @pjpenast #165
- [x] **[M]** st-switch component #166
- [x] **[M]** Finish general styles in egeo-web @alexrchies @abrahamnavas
- [x] **[M]** st-table @EvaMGC #91
- [x] **[M]** Take decission about release plan
- [ ] **[M]** Design st-fromgroup
- [ ] **[M]** st-fromgroup #88 
- [x] **[M]** Design st-list
- [ ] **[M]** st-list #87
- [x] **[M]** st-textarea #85
- [ ] **[M]** st-combobox #82
- [ ] **[M]** st-tuple #88
- [x] **[M]** st-breadcrumb #189
- [x] **[M]** Extract and separate form components desings
- [x] **[S]** Restyle API Doc
- [ ] **[S]** Meeting with CI
- [ ] **[S]** Change issue and PR templates to work with commitizen @alexrchies
- [x] **[C]** Open issue to set an avatar on @stratio user on npm @ppenalver 
- [ ] **[C]** Document egeo-cli @alexrchies @ppenalver 
- [x] **[C]** Advances about stars in repos
- [x] **[C]** Meeting about commitizen
