### ISSUE TITLE
Middle May Iteration Plan

### ISSUE THREAD

**Issue by alexrchies** [Stratio/egeo#229]
This plan captures the focus of our work during the first half of April iteration. It's a 2-week iteration. We will ship in the middle of May.

# Legend

We use the [MOSCOW notation](https://en.wikipedia.org/wiki/MoSCoW_method) to decide about the priority of tasks.

| Mark | Meaning |   
|---|---|
|  **[M]** | Must Have |
|  **[S]** | Should Have |
|  **[C]** | Could Have |
|  **[W]** | Won't Have |

# Iteration Goal

Refactor to improve consistency and confidence and add new components.

# Tasks

- [x] **[M]** st-checkbox component @pjpenast #165
- [x] **[M]** Remove index from the whole project @ppenalver 
- [x] **[M]** Design st-fromgroup @abrahamnavas @mariasantanastratio #225 
- [ ] **[M]** Update egeo-web documentation
- [ ] **[M]** Refactor Decorators
- [x] **[M]** st-picklist
- [ ] **[M]** st-list
- [ ] **[S]** Simplify Buttons
- [ ] **[S]** st-fromgroup #88 
- [ ] **[S]** st-formlist #87
- [x] **[S]** Meeting with CI
- [ ] **[S]** Change issue and PR templates @alexrchies
- [ ] **[S]** Proposals and meeting about floating items (take decissions)
- [ ] **[C]** st-tuple #88
- [ ] **[C]** Document egeo-cli @alexrchies @ppenalver
