### ISSUE TITLE
Ending May iteration plan

### ISSUE THREAD

**Issue by jcnunez-st** [Stratio/egeo#241]
This plan captures the focus of our work during the second half of May iteration. It's a 2-week iteration. We will ship at the end of May.

# Legend

We use the [MOSCOW notation](https://en.wikipedia.org/wiki/MoSCoW_method) to decide about the priority of tasks.

| Mark | Meaning |   
|---|---|
|  **[M]** | Must Have |
|  **[S]** | Should Have |
|  **[C]** | Could Have |
|  **[W]** | Won't Have |

# Iteration Goal

Refactor to improve consistency and confidence and add new components.

# Tasks

- [x] **[M]** floating elements
- [x] **[M]** Bug st-header submenu position
- [x] **[M]** Bug st-header #148
- [ ] **[M]** Update egeo-web documentation
- [x] **[M]** Refactor Decorators
- [ ] **[M]** st-list (one-list)
- [ ] **[M]** st-combobox
- [x] **[M]** Meeting with CI
- [ ] **[S]** Simplify Buttons
- [ ] **[S]** st-fromgroup #88 
- [ ] **[S]** st-formlist #87
- [ ] **[S]** Change issue and PR templates @alexrchies
- [ ] **[C]** st-tuple #88
- [ ] **[C]** Document egeo-cli @alexrchies @ppenalver
