### ISSUE TITLE
June 28th Iteration Plan

### ISSUE THREAD

**Issue by ppenalver** [Stratio/egeo#285]
You will find below the goals that have been set in order to launch the newest version 2.4.0 on June 28th

# Goal

- CI Improvements
- Page title editable
- Dinamic form generator
- Combobox component
- St-formlist component
- UX/Design Definition of notification and feedback for user
- Search with autocomplete

# Tasks
 
- [ ] CI Improvements 
- [x] Add new feature to edit page title #261
- [ ] Dinamic form generator #89
- [x] Combobox component #82
- [ ] St-formlist component #87
- [ ] UX/Design Definition of notification and feedback for user #104
- [ ] Search with autocomplete #260
- [ ] Simplify St-Button #281
- [ ] Notification/feedback components
- [ ] Starter with HMR [issue 60](https://github.com/Stratio/egeo-starter/issues/60)
- [ ] Spike for AoT library check #282
- [ ] Spike for automatic documentation generation #283
- [ ] Spike for develop demo with component and use in documentation #284
